version: 2.1

orbs:
  android: circleci/android@2.3.0


jobs:
  test:
    description: Runs unit tests and instrumented tests on the Android Library
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.04.1

    steps:
      - checkout
      - android/change-java-version:
          java-version: 8
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - run:
          name: Update Package list
          command: sudo apt-get update

      - android/create-avd:
          avd-name: customavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: customavd
          no-window: true
          restore-gradle-cache-prefix: v2
      - android/run-tests:
          test-command: ./gradlew test
      - android/run-tests:
          test-command: ./gradlew connectedAndroidTest
      - android/save-gradle-cache:
          cache-prefix: v2

  build:
    docker:
      - image: cimg/android:2023.06

    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: v2
      - android/change-java-version:
          java-version: 8

      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - run:
          name: Echo Java home
          command: echo $JAVA_HOME  
          environment:
            JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      - run:
          name: Download Dependencies
          command: ./gradlew clean

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - android/save-gradle-cache

      - run:
          name: Build Library
          command: ./gradlew assemble

  deploy:
    executor:
      name: android/android-docker
      tag: 2023.06.1
    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - android/restore-gradle-cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-gradle-cache
      - run:
          name: Publish library
          command: ./gradlew publish


  trigger-children:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
      - run:
          name: Trigger Suitcase pipeline
          command: |
            curl --location --request POST "https://circleci.com/api/v2/project/github/$CIRCLE_USERNAME/suitcase/pipeline" \
              --header 'Content-Type: application/json' \
              -u "${API_TOKEN}:" \
              --data '{"branch":"$CIRCLE_BRANCH"}' \
      - run:
          name: Trigger Tables pipeline
          command: |
            curl --location --request POST "https://circleci.com/api/v2/project/github/$CIRCLE_USERNAME/tables/pipeline" \
              --header 'Content-Type: application/json' \
              -u "${API_TOKEN}:" \
              --data '{"branch":"$CIRCLE_BRANCH"}' \
      - run:
          name: Trigger Services pipeline
          command: |
            curl --location --request POST "https://circleci.com/api/v2/project/github/$CIRCLE_USERNAME/services/pipeline" \
              --header 'Content-Type: application/json' \
              -u "${API_TOKEN}:" \
              --data '{"branch":"$CIRCLE_BRANCH"}' \

      - run:
          name: Trigger Survey pipelines
          command: |
            curl --location --request POST "https://circleci.com/api/v2/project/github/$CIRCLE_USERNAME/survey/pipeline" \
              --header 'Content-Type: application/json' \
              -u "${API_TOKEN}:" \
              --data '{"branch":"$CIRCLE_BRANCH"}' \
      
      

workflows:
  build-test-deploy-trigger-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test

      - trigger-children:
          requires:
            - deploy



